project:
  type: website
  output-dir: docs

website:
  title: "Jing Zeng"
  search: false
  favicon: profile.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - research.qmd
      - group.qmd
      - teaching.qmd
      - software.qmd
      - href: CV/CV.pdf
        text: CV
      - href: gallery.qmd
        text: Gallery
  page-footer: "Copyright 2022, Jing Zeng" 

format:
  html:
    theme: Cosmo
    css: styles.css
    # toc: true

editor: visual

