project:
  type: website
  output-dir: docs

website:
  title: "Jing Zeng"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - research.qmd
      - teaching.qmd
      - software.qmd
  page-footer: "Copyright 2022, Jing Zeng" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

